### ISSUE TITLE
Support Propeller DASH outputs with ads

### ISSUE THREAD

**Issue by igorsobreira** [cbsinteractive/bakery#104]
DASH manifests are not currently supported in Bakery:

[https://github.com/cbsinteractive/bakery/blob/0da22c6cfb55d0e44c67833c5f233e89dded9f8b/origin/propeller.go#L15-L19](https://github.com/cbsinteractive/bakery/blob/0da22c6cfb55d0e44c67833c5f233e89dded9f8b/origin/propeller.go#L15-L19)

Aha! Link: https://viacomcbs-digital.aha.io/features/BAKE-21

**Comment by krystalmejia24** [comment]
Do we have Dash clips and outputs? I have this work here https://github.com/cbsinteractive/bakery/pull/105/commits/b97a57c3700094de469ce0fc21cbedd350acaf98

I assumed it didn't. Wanted to follow up before I merge.

**Comment by Diuliani** [comment]
Open question: Should we move this feature to the backlog? 
- Most likely yes, if this feature doesn't need to be part of the feature that is being built for multi-language. We'll double-check by sprint open.

**Comment by krystalmejia24** [comment]
This issue is only for ads. https://cbs.slack.com/archives/G011XPLJLVD/p1631644009120200
