### ISSUE TITLE
bakery: drm: Configure DRM 

### ISSUE THREAD

**Issue by krystalmejia24** [cbsinteractive/bakery#106]
Placeholder to track any integration we may need with DRM. 

Both for live & vod

Aha! Link: https://viacomcbs-digital.aha.io/features/BAKE-20

**Comment by igorsobreira** [comment]
For live channels in propeller, when a channel has `drm` enabled it will have `playback_url_encrypted` field:
```
    "playback_urls_encrypted": {
        "dash": "https://cbsi679d-test9a9b-encr-dash-dev.global.ssl.fastly.net/out/v1/0e10e421c5e544bd8687fe53ac03c0d2/manifest.mpd",
        "hls": "https://cbsi679d-test9a9b-encr-hls-dev.global.ssl.fastly.net/out/v1/c8d8ca83ad434572b2358e6049ddd44c/manifest.m3u8"
    },
```

This means if a channel has DRM we can provide both `.m3u8` and `.mpd` URLs in Bakery
https://cbsinteractive.github.io/propeller/article/2020/01/07/drm.html

**Comment by aimeevitacbsi** [comment]
Comment added by Aimee Vitaglian in Aha! - [View](https://viacomcbs-digital.aha.io/comments/6898428705995472382)

This should probably be a story not a task, converting it now

**Comment by Diuliani** [comment]
Ticket canceled. Closing it.
