### ISSUE TITLE
filter to transform redundant manifest in simple ones based in a set of rules

### ISSUE THREAD

**Issue by flavioribeiro** [cbsinteractive/bakery#111]
We want to be able to apply a filter to bakery that will transform a redundant manifest in a simple one.

Example:

HTTP://origin-airspace.com/video/123/master.m3u8
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=8171676,CODECS="avc1.4d4028,mp4a.40.5",RESOLUTION=1920x1080
primary/1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=8171676,CODECS="avc1.4d4028,mp4a.40.5",RESOLUTION=1920x1080
backup/1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=6332540,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=1280x720
primary/2.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=6332540,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=1280x720
backup/2.m3u8
```

Bakery URL: HTTP://bakery-url/123/master.m3u8
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=8171676,CODECS="avc1.4d4028,mp4a.40.5",RESOLUTION=1920x1080
primary/1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=6332540,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=1280x720
primary/2.m3u8
```
From the top of my head, I think we could have one initial rule:

1) Check if renditions from the master are healthy (not 404ing and `Last-Modified-Time` is smaller than 2x Segment length). If master renditions are healthy, filter backup renditions out.

Refs https://github.com/cbsinteractive/propeller/issues/1083

**Comment by krystalmejia24** [comment]
@flavioribeiro how are these manifests listed in the manifest? Is the first variant the master/primary? I'm not sure how I would select master, for now Im simply selecting first variant in the list for health checks

**Comment by krystalmejia24** [comment]
@flavioribeiro why does `Last-Modified-Time` have to be greater than 2x segment length?

**Comment by scollins-cbsi** [comment]
closing.

**Comment by scollins-cbsi** [comment]
https://cbsinteractive.github.io/bakery/filters/de-weave.html
