### ISSUE TITLE
bakery: Check for redundant stream in manifest prior to deweaving

### ISSUE THREAD

**Issue by krystalmejia24** [cbsinteractive/bakery#121]
[https://cbs.slack.com/archives/GHW277JS2/p1592947825060300?thread\_ts=1592947825.060300](https://cbs.slack.com/archives/GHW277JS2/p1592947825060300?thread_ts=1592947825.060300)

We want to ensure we aren't applying the deweave filter if a request is made for a non redundant manifest.

Aha! Link: https://viacomcbs-digital.aha.io/features/BAKE-17

**Comment by Diuliani** [comment]
Ticket canceled. Closing it.
