### ISSUE TITLE
add documentation with supported filters

### ISSUE THREAD

**Issue by flavioribeiro** [cbsinteractive/bakery#13]

**Comment by zsiec** [comment]
Added a draft here: https://github.com/cbsinteractive/bakery/tree/remove-text-as#supported-filters

**Comment by krystalmejia24** [comment]
Merged something in this PR [here](https://github.com/cbsinteractive/bakery/pull/26).

Playing with jekyll themes to get something up and running that follows the propeller model

**Comment by krystalmejia24** [comment]
https://cbsinteractive.github.io/bakery
