### ISSUE TITLE
Bakery to front dictate for Webvtt failures

### ISSUE THREAD

**Issue by aimeevitacbsi** [cbsinteractive/bakery#134]
As CBS Sports, I can use bakery to front all dictate URLS so that I can protect against content failure stemming from WebVTT failures.

**Acceptance Criteria:**

- Bakery URLs are used to proxy Dictate URLs
- In the event dictate fails or WebVTT files are not present, Bakery returns empty manifests
- Change is validated on CBSi Avia Player

**Requirements:**

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [x] <span data-href="#aha_task_list_BAKE-33-1" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/> implement PreventHTTPStatusError filter
    <br/>
- [x] Deploy to production
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://viacomcbs-digital.aha.io/features/BAKE-33

**Comment by aimeevitacbsi** [comment]
Comment added by Aimee Vitaglian in Aha! - [View](https://viacomcbs-digital.aha.io/comments/6923310954702940525)

[ **flavio.ribeiro** ](https://app.slack.com/team/W011YVB0T6V) [6:48 PM](https://cbs.slack.com/archives/C011XPF6E07/p1611888514002000)

one thing we discussed in a call on the Sports HQ P1 right now: we’re thinking about having bakery in front of all dictate related url’s on the manifests and have bakery return empty manifests in the event that the real webvtts are not present for some reason (and there are N reasons why the webvtt might not be present). I’m writing this here so we keep track of this feature to be built in dictate + bakery at some point _in the future™_

related thread [https://cbs.slack.com/archives/CBXVDLCUR/p1611885866113600](https://cbs.slack.com/archives/CBXVDLCUR/p1611885866113600)

**Comment by zsiec** [comment]
Deployed @ 15:30 eastern via `v0.1.14`
