### ISSUE TITLE
Import Propeller Client into project to avoid dependencies on private repos

### ISSUE THREAD

**Issue by krystalmejia24** [cbsinteractive/bakery#145]
Since this is an open-source project, I think it would be best to import the propeller client into the repository to avoid any of the permission issues that outside collaborators have been experiencing.

We can create a `/clients` directory and store the client there.

Aha! Link: https://viacomcbs-digital.aha.io/features/BAKE-37

**Comment by krystalmejia24** [comment]
refs https://github.com/cbsinteractive/bakery/issues/143

**Comment by Diuliani** [comment]
Closing tkt - Cancel until further notice.
