### ISSUE TITLE
Dash Tile Thumbsheets does not works after going through bakery manipulator service

### ISSUE THREAD

**Issue by jigneshdhruv** [cbsinteractive/bakery#15]

**Comment by zsiec** [comment]
The go-dash parser needs to be extended to support the values used in the thumbsheet representation. In this case, this element need to be supported: 
`<EssentialProperty schemeIdUri="http://dashif.org/thumbnail_tile" value="10x10"/>`

**Comment by krystalmejia24** [comment]
We have a PR [here](https://github.com/zencoder/go-dash/pull/73) in go-dash that will fix this issue

**Comment by krystalmejia24** [comment]
Ive merged into our branch for now and have confirmed this is now working in dev.
