### ISSUE TITLE
 bakery: Codec filtering should cover HDR cases

### ISSUE THREAD

**Issue by flavioribeiro** [cbsinteractive/bakery#33]
We need to be able to filter out HDR and non-HDR streams for both HLS and DASH.

**Comment by zsiec** [comment]
When differentiating between HEVC with HDR10 and SDR HEVC:

I think we can get the profile value out of the codec string, the `general_profile_idc` is the sent as `2` in this codec string `hvc1.2.4.L93.50` and as `1` in this string `hvc1.1.6.L123.50`
`2`=`main10`
`1`=`main`
`3`=`still_picture`

We can pretty safely assume `main10` = HDR10 if the codec string starts with `hvc` or `hev`
it’s not perfect, but good enough for this usecase
```
hvc1.1.6.L123.50 
     ^---parse this value
```

**Comment by zsiec** [comment]
<img width="658" alt="Screen Shot 2020-03-02 at 5 18 31 PM" src="https://user-images.githubusercontent.com/495628/75787139-437a6a00-5d34-11ea-87ec-036a94181198.png">

Page 20-21
https://www.etsi.org/deliver/etsi_ts/103200_103299/103285/01.01.01_60/ts_103285v010101p.pdf
