### ISSUE TITLE
bakery: ability to re-label audio description tags

### ISSUE THREAD

**Issue by flavioribeiro** [cbsinteractive/bakery#35]
We'd like to be able to replace audio description tags for roku.

@jigneshdhruv can you paste here some examples and the diff between normal and roku manifests?

**Comment by krystalmejia24** [comment]
currently being tested by Player team.

**Comment by krystalmejia24** [comment]
first iteration of this was done by targeting the roku accessibility issue. if we need any more issues around audio description, lets file another ticket.
