### ISSUE TITLE
bakery: ability to redirect playback url's to propeller channels

### ISSUE THREAD

**Issue by flavioribeiro** [cbsinteractive/bakery#36]
We would like to have a fixed playback URL that will redirect the user to the real one.

Example:

Given the organization `mtv123` and the channel ID `awards123`, we could infer a playback URL like this: `http://bakery.cbsi.video/propeller/mtv123/awards123.m3u8`. 

This URL would hit the Propeller API (via its CDN endpoint) and route the user to their `playback_url` (it could `301 Redirect` or simply parse the manifest and point the  rendition manifests to absolute urls).

**Comment by keithrichardscbs** [comment]
This is great for our case of wanting to have known playback urls before they are created. Also gives us huge flexibility with bakery filtering.

**Comment by flavioribeiro** [comment]
the business case: now that we can pass channel ID's (https://cbsinteractive.github.io/propeller/whats-new/2020/02/24/whats-new-in-propeller.html) to the channels, this feature would add the capability of having the playback URL ahead of time. We could even create a [new channel state in propeller](https://cbsinteractive.github.io/propeller/api/channel.html#channel-status) that's `SCHEDULED` by relying on this functionality.
