### ISSUE TITLE
hls: trim live hls stream to specified start/end and return VOD playlists for variants

### ISSUE THREAD

**Issue by zsiec** [cbsinteractive/bakery#37]
For the Big Brother usecase, we need to be able to harvest up to 24 hours of video off the live streams every day. Mediahub will take care of generating these VODs, but expects a correctly trimmed VOD HLS stream as input. Bakery will be responsible for generating this VOD HLS stream for Mediahub based on the config defined by Propeller.

The Propeller team is setting up a MediaStore container where they will push clear streams from MediaLive. The live stream will retain segments and return variant playlists with up to 48 hours of content.

In order to fetch content from only the last 24h, requests will be made to bakery with a start and end time specifying what parts of the manifest to include in the modified stream.

Assuming:
1) We define a filter named `trim` where the syntax is `t(start,end)` (initial thought is to use 64-bit UNIX time for these values)
2) Propeller exposes the clear stream url in their channel payload: example http://propeller-api.cbsivideo.com/v1/organization/gamesg041/channel/pokemf87h
3) The stream url contains valid `#EXT-X-PROGRAM-DATE-TIME` tags with content inside the range requested in the `trim` filter

The initial proposal is to interpret a master manifest URL like:
https://bakery.cbsi.video/t(start,end)/propeller/gamesg041/channel/pokemf87h.m3u8

When Bakery sees this request, it will:
1) Request the live stream url from Propeller's API
2) Re-write the media manifest URLs to point to bakery, passing through the trimming config, generating media manifest urls like: `https://bakery.cbsi.video/t(start,end)/propeller/gamesg041/channel/pokemf87h/<base64-encoded-original-media-manifest-url>.m3u8`

When Bakery sees this media manifest, it will:
1) Parse out the base64 encoded url, decode and fetch manifest contents
2) Trim out any segments outside the defined `trim` range
3) Append an `#EXT-X-ENDLIST` to the end of the manifest
4) Rewrite segment urls if they are relative, to ensure they are coming from the original source

The stream propeller exposes for harvesting these VODs will require an auth mechanism, (likely a custom header) Bakery will need to figure out how this will be configured and ensure the auth header is sent on all requests to the the source stream.

**Comment by krystalmejia24** [comment]
@zsiec @allisonnicoledeal do you have a stream I can test with? I can create a test clip in propeller im mostly trying to wrap my head around the playlist type? Is it live with a sliding window or is it VOD and it will have the full list of segments advertised in the manifest?

**Comment by krystalmejia24** [comment]
Currently in DEV until it is tested.
