### ISSUE TITLE
bakery: order language & captions tracks (define what language should come first)

### ISSUE THREAD

**Issue by flavioribeiro** [cbsinteractive/bakery#5]
Aha! Link: https://viacomcbs-digital.aha.io/features/BAKE-29

**Comment by krystalmejia24** [comment]
There is a blocker on DASH where player manages selection priority. Currently we can only target defaults in HLS using Media Alternatives found in master playlist

**Comment by Diuliani** [comment]
Ticket canceled. Closing it.
