### ISSUE TITLE
Manage Propeller Output Groups

### ISSUE THREAD

**Issue by krystalmejia24** [cbsinteractive/bakery#55]
We will need to update how Bakery proxies propeller channels as there is work being done to support multiple [output groups](https://github.com/cbsinteractive/propeller/issues/790)

An idea is:
`bakery-hostname/propeller/<org-id>/<channel-id>/<output-group-id>.m3u8`

**Comment by krystalmejia24** [comment]
@igorsobreira given the work youve been doing is it ok for us to "assign" this to you so we can track the progress on the bakery side?

**Comment by igorsobreira** [comment]
@krystalmejia24 no problem. But what else is needed here now that #98 is merged?

**Comment by krystalmejia24** [comment]
@igorsobreira perfect just wanted to know that it was safe to close and that you weren't doing any extra qa on your side!
